markdown: kramdown
theme: jekyll-theme-minimal
title: Vincent Charlebois
description: Interdisciplinary Creative Technologist, Artist and Developer
logo: https://www.charlebois.solutions/1mg/__desaturate__dataviz.png
